add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$azure\
$python\
$terraform\
$kubernetes\
$character\
"""

[time]
disabled = false
format = "[$time]($style)"
style = "bright black"
time_format = "[%H:%M] "

[username]
format = "[$user]($style)"
disabled = false
show_always = true
style_user = "blue"

[character]
success_symbol = "[|](bold green)"
error_symbol = "[|](bold red)"

[directory]
format = ":[$path]($style) "
style = "bold red"

[git_branch]
format = "[$branch]($style) "
style = "green"

[git_status]
style = "green"

[aws]
format = "[$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)"
symbol = " "

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
style = "bold cyan"

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "purple bold"

[terraform]
format = '[$symbol $version \[$workspace\]]($style) '
symbol = "󱁢"
version_format = "v${raw}"
