add_newline = false

format = """
$time\
$kubernetes\
$python\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$character\
"""

[time]
disabled = false
format = "[$time]($style)"
style = "bright black"
time_format = "[%H:%M] "

[username]
format = "[$user]($style)"
disabled = false
show_always = true
style_user = "blue"

[character]
success_symbol = "[|](bold red)"
error_symbol = "[|](bold red)"

[directory]
format = ":[$path]($style) "
style = "bold purple"

[git_branch]
format = "[$branch]($style) "
style = "green"

[git_status]
style = "green"

[aws]
format = "[$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)"
symbol = " "

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
