return {
	{
		"ThePrimeagen/harpoon",
		branch = "harpoon2",
		dependencies = { "nvim-lua/plenary.nvim" },
		config = function()
			local harpoon = require("harpoon")

			harpoon:setup()

			vim.keymap.set("n", "<leader>ma", function()
				harpoon:list():add()
			end, { desc = "Harpoon append" })
			vim.keymap.set("n", "<leader>me", function()
				harpoon.ui:toggle_quick_menu(harpoon:list())
			end, { desc = "Harpoon toggle menu" })

			-- Qwerty
			vim.keymap.set("n", "<leader>mh", function()
				harpoon:list():select(1)
			end, { desc = "Harpoon switch to 1" })
			vim.keymap.set("n", "<leader>mj", function()
				harpoon:list():select(2)
			end, { desc = "Harpoon switch to 2" })
			vim.keymap.set("n", "<leader>mk", function()
				harpoon:list():select(3)
			end, { desc = "Harpoon switch to 3" })
			vim.keymap.set("n", "<leader>ml", function()
				harpoon:list():select(4)
			end, { desc = "Harpoon switch to 4" })

			vim.keymap.set("n", "<leader>m1", function()
				harpoon:list():select(1)
			end, { desc = "Harpoon switch to 1" })
			vim.keymap.set("n", "<leader>m2", function()
				harpoon:list():select(2)
			end, { desc = "Harpoon switch to 2" })
			vim.keymap.set("n", "<leader>m3", function()
				harpoon:list():select(3)
			end, { desc = "Harpoon switch to 3" })
			vim.keymap.set("n", "<leader>m4", function()
				harpoon:list():select(4)
			end, { desc = "Harpoon switch to 4" })
			vim.keymap.set("n", "<leader>m5", function()
				harpoon:list():select(5)
			end, { desc = "Harpoon switch to 5" })
			vim.keymap.set("n", "<leader>m6", function()
				harpoon:list():select(6)
			end, { desc = "Harpoon switch to 6" })
			vim.keymap.set("n", "<leader>m7", function()
				harpoon:list():select(7)
			end, { desc = "Harpoon switch to 7" })
			vim.keymap.set("n", "<leader>m8", function()
				harpoon:list():select(8)
			end, { desc = "Harpoon switch to 8" })
			vim.keymap.set("n", "<leader>m9", function()
				harpoon:list():select(9)
			end, { desc = "Harpoon switch to 9" })
			vim.keymap.set("n", "<leader>m0", function()
				harpoon:list():select(10)
			end, { desc = "Harpoon switch to 10" })

			vim.keymap.set("n", "<leader>m!", function()
				harpoon:list():select(1)
			end, { desc = "Harpoon switch to 1" })
			vim.keymap.set("n", "<leader>m@", function()
				harpoon:list():select(2)
			end, { desc = "Harpoon switch to 2" })
			vim.keymap.set("n", "<leader>m#", function()
				harpoon:list():select(3)
			end, { desc = "Harpoon switch to 3" })
			vim.keymap.set("n", "<leader>m$", function()
				harpoon:list():select(4)
			end, { desc = "Harpoon switch to 4" })
			vim.keymap.set("n", "<leader>m%", function()
				harpoon:list():select(5)
			end, { desc = "Harpoon switch to 5" })
			vim.keymap.set("n", "<leader>m^", function()
				harpoon:list():select(6)
			end, { desc = "Harpoon switch to 6" })
			vim.keymap.set("n", "<leader>m&", function()
				harpoon:list():select(7)
			end, { desc = "Harpoon switch to 7" })
			vim.keymap.set("n", "<leader>m*", function()
				harpoon:list():select(8)
			end, { desc = "Harpoon switch to 8" })

			-- Toggle previous & next buffers stored within Harpoon list
			vim.keymap.set("n", "<leader>mp", function()
				harpoon:list():prev()
			end, { desc = "Harpoon previous" })
			vim.keymap.set("n", "<leader>mn", function()
				harpoon:list():next()
			end, { desc = "Harpoon next" })
		end,
	},
}
