import = [
    # "~/.config/alacritty/catppuccin-latte.toml",
    # "~/.config/alacritty/catppuccin-frappe.toml",
    "~/.config/alacritty/catppuccin-macchiato.toml",
    # "~/.config/alacritty/themes/themes/tokyo-night.toml",
]

[env]
TERM = "alacritty"

[font]
size = 18

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[scrolling]
history = 10000

[shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "full"
opacity = 0.8
dynamic_padding = true

[window.padding]
# x = 0
# y = 0
